# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'challenge-food' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for challenge-food
pod 'Alamofire', '~> 5.5'
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'SDWebImage', '~> 5.0'

  target 'challenge-foodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'challenge-foodUITests' do
    # Pods for testing
  end

end
